### PR TITLE
feat: always preserve json-rpc errors

### PR DESCRIPTION
**Pull request by stambata**
preserve error format (type, message and errorPrint) when receiving json-rpc errors.

### CODE REVIEW

**Review by zetxx — APPROVED** [review]

**Comment by kalinkrustev** [comment]
Please see ca09a922e13b708427ef182d5eb26fca7b5118a1. I prefer to convert the error to a known one, instead of throwing plain Error, because we may need to use instanceof in some place. If you still need it this way, we need to discuss use cases or fallback to plain error after looking for a known one.

**Comment by stambata** [comment]
@kalinkrustev The proposed change is good but only in the cases when we have a predefined list of errors in the local ut-error collection. The problem is when we have multiple UT implementations (services) which communicate with each other over http (e.g. l1p). In a case like that when one of the services returns a well formatted error (with type, print, etc...) the caller service overrides it and the error details get lost.
Relying on utError.get would mean that we need to have all errors replicated in all the services (or to somehow have a  central errors registry shared between services).

So for the moment I propose extending your proposal like this:
```
...
var plainError = cause => Object.assign(new Error(), cause);
module.exports = {
    rpc: function(cause) {
        var error = RPC;
        if (cause && cause.type) {
            error = utError.get(cause.type) || plainError;
        }
        return error(cause);
    },
    ...
}
```

**Comment by stambata** [comment]
Please see the latest diff: https://github.com/softwaregroup-bg/ut-port-jsonrpc/pull/4/files

**Comment by kalinkrustev** [comment]
> the caller service overrides it and the error details get lost

How is it lost? It should go in the cause property of the RPC error.
We should keep plain errors to minimum (even eliminate entirely), as it will be quite hard to react to them properly. Wrapping the original error in RPC, will allow us to know more about the error, not less.

If you mean that logging is not showing it, then let's improve logging.

**Comment by stambata** [comment]
So here's an example from l1p describing why I needed it this way:

1) the login component calls the backend with method 'identity.check'
2) the backend receives the request but there's no ut-user, ut-identity or even a database... so it dispatches it to a remote service over http.
3) that other service performs some identity checks and returns an error
4) the http client of the first service receives that error (with type policy.param.password or identity.invalidCredentials) but it doesn't know what it means so it creates another error from it with type PortRPC
5) the front-end receives the altered error and doesn't know what to do with it as it expects errors with certain types.

**Comment by stambata** [comment]
Currently the described functionality is achieved by writing custom 'identity.check.response.receive' hook instead of using the default ut-port-jsonrpc receive handler. But it would be good if we could figure out a way how we can maintain a common list of errors which are distributed across 10 different remote services with 10 different ut-error collections and make sure they follow the same format when transferred from service to service.

**Comment by kalinkrustev** [comment]
OK, now I understand. I will think about it, maybe what you want should be enabled with setting.

**Comment by kalinkrustev** [comment]
Will this work for the case you described?
```js
var plainError = cause => Object.assign(new Generic(), cause);
```
I.e. instead of Error(), call Generic()

**Comment by stambata** [comment]
Yes, this way should work perfectly as the respective proterties will be overriden by the cause and instanceof check will still work.

**Pull request merged**
